name: 'first_action'

# on -> means when to trigger the action
on:
  push:
    # when push to this branch
    branches:
      - master

# jobs: many jobs construct a whole Action
jobs:
  call-api:
    runs-on: ubuntu-latest
    # declare the detail of jobs
    steps:
      - name: 'checkout'
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2 # setup python runtime env
        with: 
          python-version: 3.6 #install the python needed
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: run python script
        run: |
            python main.py